#!/bin/bash

maxsize=300000 # 300kb limit
item="$1"
filesize=$(stat -c%s "$item")
type=$(file -b --mime-type "$item")

if [  "$type" = application* ]; then
	exit 7
elif (( filesize > maxsize )); then
    message "ERROR: File size is over the limit. 300kb"
    exit 7
else
	exit 0
fi
