#!/bin/sh


curl_file(){	# download by url git repo file to local 
	# https://raw.githubusercontent.com/username/repo/master/file
	item=$(echo "$1" |
		sd 'github.com' 'raw.githubusercontent.com'|
		sd 'blob/' '')

	filename=$(echo "$item" |awk -F'/' '{print $(NF)}')
	echo "$filename"
	
	curl -o "$filename" "$item"
}

curl_file "$@"
