#!/bin/sh
#FILE! download file from github file link

# https://raw.githubusercontent.com/username/repo/master/file
item="$@"
[ ! "$item" ] && color 'Error: empty args'

item=$(echo "$item" |
	sd 'github.com' 'raw.githubusercontent.com'|
	sd 'blob/' '')

filename=$(echo "$item" |awk -F'/' '{print $(NF)}')
echo "$filename"

curl -o "$filename" "$item"

