#!/bin/sh


curl_file(){	# download by url git repo file to local 
	# https://raw.githubusercontent.com/username/repo/master/file
	item=$(echo "$2" |
		sd 'github.com' 'raw.githubusercontent.com'|
		sd 'blob/' '')

	filename=$(awk -F'/' '{print $(NF)}' <<<"$item")
	echo "$filename"
	
	curl -o "$filename" "$item"
}

curl_file "$@"
