#!/bin/sh

item=
option=


case $1 in
  '-s' | '--sub') option='sub'; item="$2" ;;
  '-e'| '--echo') option='echo'; item="$2" ;;
  *) item="$1" ;;
esac


[ -z "$item" ] && color 'Missing: Argument: name?' >&2  && exit 7
[ ! "$item" ] && color 'Missing: Argument: name?'  >&2  && exit 7


cp "$TT_VAR/template.sh" "$item"
chmod 700 "$item"


_open(){
	if item=$(realpath $item); then
		st open "$item"
	fi
}

_getpath(){
	realpath "$item"
}

case "$option" in
  'sub')  _open ;;
  'echo') _getpath ;;
  *) color 'Error: unknown' ;;
esac

exit $?
