#!/bin/sh


__auto(){
	
	local item
	old="${READLINE_LINE}"
	if [ -z $old ]; then
		item=$(_get_script_file)
	else
		item="$old"
	fi

	subitem=$(hpp $item | fuzzy one | cut -d ' ' -f1)
	# item=$(echo "$item" one)

	READLINE_LINE="${item} ${subitem}"
	READLINE_POINT=${#READLINE_LINE}

}

_get_script_file(){

	# cd  |
	item=$(fdls --base-directory "$TT_BASH/scripts" |fuzzy one)
	# cd "$OLDPWD"
	echo "$item"
}

__script_complete(){	# completion sub commands

	old="${READLINE_LINE}"

	item=$(_get_script_file)

	READLINE_LINE="${old}${item}"
	READLINE_POINT=${#READLINE_LINE}

	
}


__cmd_complete(){
	
	old="${READLINE_LINE}"

	all=$(
	{
	    declare -F | awk '{print $3}' | grep -v '^__'
	    alias | awk -F'[ =]' '{print $2}'
	    export | cut -d "=" -f 1 | awk '{print "$"$3}'
	} | sort -u | fzy
	)

	# _append $all
	READLINE_LINE="${old}${all}"
	READLINE_POINT=${#READLINE_LINE}
	
}


__last() {

	item=$(history  1 | cut -c 8- \
		| warp head '$('|warp tail ')')
    READLINE_LINE="${READLINE_LINE}${item}"
	READLINE_POINT=0
	# READLINE_POINT=${#READLINE_LINE}

}
