#!/bin/bash
#FILE! on_exit functions


__on_exit() {
    echo "TERABO Performing cleanup tasks..."

    set_var "RG_options" "${RG_options}"
}

resource() {
  . "$TT_BASH/shared"
  echo 'source shared variable done...'
}

# Set up trap to execute resource on receiving SIGUSR1
trap 'resource' SIGUSR1

# Export function Area


export VART=1
export -f set_var
export -f get_var
export -f list_var
export -f set_recents

trap __on_exit EXIT
