#!/bin/bash
#FILE! on_exit functions


__on_exit() {
    echo "TERABO Performing cleanup tasks..."
}

VAR_HANDLER(){

    item=$(cat "$TT_IPC")
    # wait
    export "$item"

}

trap 'VAR_HANDLER' SIGRTMIN

CD_HANDLER(){

    item=$(cat "$TT_IPC")
    # wait
    cd "$item" || return

}

trap 'CD_HANDLER' SIGUSR2

# Export function Area

export -f set_var
export -f get_var
export -f list_var
export -f set_recents

trap __on_exit EXIT
