#!/bin/bash
#FILE! on_exit functions


__on_exit() {
    echo "TERABO Performing cleanup tasks..."
}

var_handle(){
    
    item=$(cat ~/ipcvar)
    wait
    export $item

}

trap 'var_handle' SIGRTMIN

# Export function Area

export -f set_var
export -f get_var
export -f list_var
export -f set_recents

trap __on_exit EXIT
