#!/bin/bash
#FILE! show messaging echo

success(){
  return $?
}

failed(){

  if [ $? -ne 0 ]; then
      return 7
  else
      return 0
  fi
}

inputs(){

  promp=`color -i 2 "${2}: ❯ "`

  read  -erp "$promp" -i "$3" inputs

  if [ -z "$inputs" ]; then
    echo 'empty'
    exit 7
  else
    echo "$inputs"
  fi

}


confirm() {
  promp=`color 'confirm : (y/n): ❯ '`
  read -rp "$promp" confirm
  if [ "$confirm" = "y" ]; then
    return 0
  else
    return 7
  fi
}

message(){
  all="$*"
  color "$all"
}

export -f confirm
export -f message
export -f inputs
export -f success
export -f failed
