#!/bin/bash
#FILE! show messaging echo

success(){
  return $?
}

failed(){

  if [ $? -ne 0 ]; then
      return 7
  else
      return 0
  fi
}

confirm() {
  promp=`color 'confirm : (y/n): ❯ '`
  read -rp "$promp" confirm
  if [ "$confirm" = "y" ]; then
    return 0
  else
    return 7
  fi
}

message(){
  all="$*"
  color "$all"
}

export -f confirm
export -f message
export -f inputs
export -f success
export -f failed
