#!/bin/bash
#FILE! show messaging echo


show_input(){
  read  -erp "${BOLD}${1}${ARROW} " -i "${2}" new
  echo "$new"
}


show_confirm() {

  read -p "Confirmation: (y/n) ❯" confirm
  if [ "$confirm" = "y" ]; then
    "$@"
  else
    echo "User canceled the Operations..."
  fi
}

show_msg2(){
  echo -e "${BMAGENTA}${1}${END} ${BOLD}${2}${END}"
}

export -f show_confirm
export -f show_msg2
export -f show_input
