#!/bin/bash
#FILE! prompt area

# ❯ ⬢ 

__track_pwd() {
	# Get the current directory
	last_pwd=$(get_var 'LastPWD')
	current_dir="$PWD"

	#check if last and current is same
	[[ "$last_pwd" == "$current_dir" ]] && return

	# Record the current directory in a file
	set_recents 'LastPWD' "$current_dir"

}

__cd_last_PWD(){

	ifile=$(get_var_file 'LastPWD')
	dir=$(sed -n '2p' "$ifile")

	[ -d "$dir" ] && cd "$dir" || return
	sed -i '1d' "$ifile"
}


__last_time=$(get_var 'Timer')
[ ! "${__last_time}" ] && __last_time=$(date +%s)


_run_ads(){

	current_time=$(date +%s)
	time_diff=$((current_time - __last_time))
	
	hour=$((60 * 15))

	if [[ $time_diff -ge $hour ]]; then

		advertise
		__last_time="$(date +%s)"
		set_var 'Timer' "$__last_time"

	fi
}

PROMPT_COMMAND="_run_ads;$PROMPT_COMMAND"
PROMPT_COMMAND="__track_pwd;$PROMPT_COMMAND"

