#!/bin/bash
#TITLE! test expand semi word

thefile="$(which color)"
rg '^ansi::(\w+)' -o "$thefile" |
warp head 'color=$(' | warp tail '); shift; text="$1"; ;;' > "$TT_TEMP"

rg '^ansi::(\w+)' -or '$1' "$thefile" | warp head '--' | warp tail ')' |
paste - "$TT_TEMP"


