#!/bin/sh
#FILE! Advertise COMMAND of the DAY

db_file="$TT_PATTERN/advertise.ttdb"

advertise_index=1
advertise_index=24

show_time(){

	dayOfWeek=$(date +"%A")
	dateDay=$(date +"%d")

	echo -e "Today is ${CYAN}${dayOfWeek}${END}, $(date +"%B") ${BCYAN}${dateDay}${END}, $(date +"%Y")"
}

show_ads() {
	
	item=$(awk "NR==${advertise_index}" "$db_file")
	count=$(wc -l < "$db_file")

	advertise_index=$((1 + $advertise_index % $count))

	sed -i '7c'"advertise_index=${advertise_index}" "${0}"
	echo "$item" | rg '#|[.]\w+'
}

generate_db(){
	> "$db_file"
	{
		generate_help jump
		generate_help warp
		generate_help play
		generate_help refactor
	} | shuf > "$db_file"
}

view(){
	cat "$db_file"
}

sub(){
	st open "$db_file"
}

generate_help(){	# display help info
	item=$(which "$1")
	name=$(basename "$item")
	rg '^[.]?[a-z]+.*\b\(' "${item}" -N | 
	sd '\(\)\s*\{?' '' | rg '#' | 
	warp head "$name"
}

#TODO! List todo and Task ,IDea from .md
if [ "$#" -gt 0 ]; then

	"$1" "$@" 

else
	echo
	echo "Ads by" "TERABO"
	show_ads
fi

