#!/bin/sh

INDEX=0
SEP=':'


case ${1} in
-f) SEP=${2} shift 2 ;;
-i) INDEX=${2} shift 2 ;;
\? | :) echo "Invalid option: $1" 1>&2 ;;
esac

case ${1} in
-f) SEP=${2} shift 2 ;;
-i) INDEX=${2} shift 2 ;;
\? | :) echo "Invalid option: $1" 1>&2 ;;
esac


clr(){

    awk -v sep="$SEP" -v idx="$INDEX" \
    'BEGIN {
        FS = (sep == "" ? ":" : sep);

        colors[3] = "\033[1;2m"; # bold; grey
        colors[2] = "\033[1m"; # bold
        colors[4] = "\033[0;38;5;34m"; # green hex

        colors[5] = "\033[1;30m"; # cyam
        colors[6] = "\033[35m";
        colors[7] = "\033[32m";

        colors[1] = "\033[38;2;0;0;0m"; # black
        }
        {
            str = ""
            for(i=1;i<=NF;i++){
                str = sprintf("%s%s%s\033[0m", str, colors[(i+idx) % 7 + 1], $i);
                
                if( i!=NF ){str = sprintf("%s%s%s\033[0m", str, colors[2], sep);}
            }
            printf "%s\n", str;
        }'

}

if [ ! -t 0 ]; then
    clr
 else
    echo "$@" | clr
fi


