#!/bin/bash

ANSI_ESC=$'\033'
ANSI_CSI="${ANSI_ESC}["
# ANSI_OSC="${ANSI_ESC}]"
# ANSI_ST="${ANSI_ESC}\\"


RESETBG=`printf '%s49m' "$ANSI_CSI"`
RESETCOLOR=`printf '%s0m' "$ANSI_CSI"`
RESETFG=`printf '%s39m' "$ANSI_CSI"`
WHITE=`printf '%s37m' "$ANSI_CSI"`
WHITE2=`printf '%s97m' "$ANSI_CSI"`
YELLOW=`printf '%s33m' "$ANSI_CSI"`
YELLOW2=`printf '%s93m' "$ANSI_CSI"`
BLACK=`printf '%s30m' "$ANSI_CSI"`
BLACK2=`printf '%s90m' "$ANSI_CSI"`
BLUE=`printf '%s34m' "$ANSI_CSI"`
BLUE2=`printf '%s94m' "$ANSI_CSI"`
CYAN=`printf '%s36m' "$ANSI_CSI"`
CYAN2=`printf '%s96m' "$ANSI_CSI"`
MAGENTA=`printf '%s35m' "$ANSI_CSI"`
MAGENTA2=`printf '%s95m' "$ANSI_CSI"`
RED=`printf '%s31m' "$ANSI_CSI"`
RED2=`printf '%s91m' "$ANSI_CSI"`
GREEN=`printf '%s32m' "$ANSI_CSI"`
GREEN2=`printf '%s92m' "$ANSI_CSI"`
BGBLACK=`printf '%s40m' "$ANSI_CSI"`
BGBLACK2=`printf '%s100m' "$ANSI_CSI"`
BGBLUE=`printf '%s44m' "$ANSI_CSI"`
BGBLUE2=`printf '%s104m' "$ANSI_CSI"`
BGCYAN=`printf '%s46m' "$ANSI_CSI"`
BGCYAN2=`printf '%s106m' "$ANSI_CSI"`
BGGREEN=`printf '%s42m' "$ANSI_CSI"`
BGGREEN2=`printf '%s102m' "$ANSI_CSI"`
BGMAGENTA=`printf '%s45m' "$ANSI_CSI"`
BGMAGENTA2=`printf '%s105m' "$ANSI_CSI"`
BGRED=`printf '%s41m' "$ANSI_CSI"`
BGRED2=`printf '%s101m' "$ANSI_CSI"`
BGWHITE=`printf '%s47m' "$ANSI_CSI"`
BGWHITE2=`printf '%s107m' "$ANSI_CSI"`
BGYELLOW=`printf '%s43m' "$ANSI_CSI"`
BGYELLOW2=`printf '%s103m' "$ANSI_CSI"`
BOLD=`printf '%s1m' "$ANSI_CSI"`
FRAKTUR=`printf '%s20m' "$ANSI_CSI"`
FRAME=`printf '%s51m' "$ANSI_CSI"`
FAINT=`printf '%s2m' "$ANSI_CSI"`
UNDERLINE=`printf '%s4m' "$ANSI_CSI"`
BLINK=`printf '%s5m' "$ANSI_CSI"`
BELL=`printf "%s" $'\007'`

ansi::rgb() {
    printf '%s38;2;%s;%s;%sm' "$ANSI_CSI" "$1" "$2" "$3"
}

ansi::bgRgb() {
    printf '%s48;2;%s;%s;%sm' "$ANSI_CSI" "$1" "$2" "$3"
}

ansi::bgColor() {
    printf '%s48;5;%sm' "$ANSI_CSI" "$1"
}

ansi::color() {
    printf '%s38;5;%sm' "$ANSI_CSI" "$1"
}

ansi::resetbg() {
    printf '%s49m' "$ANSI_CSI"
}

ansi::resetcolor() {
    printf '%s0m' "$ANSI_CSI"
}

ansi::resetfg() {
    printf '%s39m' "$ANSI_CSI"
}


# ============================ Color


# Function to print text in specified color using ANSI escape codes
clr() {
    local color
    local text
    local result=""

    while [ $# -gt 0 ]; do
        case "$1" in
        --bell)         color="$BELL"; shift; text="$1"; ;;
        --bgblack2)     color="$BGBLACK2"; shift; text="$1"; ;;
        --bgblack)      color="$BGBLACK"; shift; text="$1"; ;;
        --bgblue2)      color="$BGBLUE2"; shift; text="$1"; ;;
        --bgblue)       color="$BGBLUE"; shift; text="$1"; ;;
        --bgcolor)      color="$BGCOLOR"; shift; text="$1"; ;;
        --bgcyan2)      color="$BGCYAN2"; shift; text="$1"; ;;
        --bgcyan)       color="$BGCYAN"; shift; text="$1"; ;;
        --bggreen2)     color="$BGGREEN2"; shift; text="$1"; ;;
        --bggreen)      color="$BGGREEN"; shift; text="$1"; ;;
        --bgmagenta2)   color="$BGMAGENTA2"; shift; text="$1"; ;;
        --bgmagenta)    color="$BGMAGENTA"; shift; text="$1"; ;;
        --bgred2)       color="$BGRED2"; shift; text="$1"; ;;
        --bgred)        color="$BGRED"; shift; text="$1"; ;;
        --bgrgb)        color="$BGRGB"; shift; text="$1"; ;;
        --bgwhite2)     color="$BGWHITE2"; shift; text="$1"; ;;
        --bgwhite)      color="$BGWHITE"; shift; text="$1"; ;;
        --bgyellow2)    color="$BGYELLOW2"; shift; text="$1"; ;;
        --bgyellow)     color="$BGYELLOW"; shift; text="$1"; ;;
        --black2)       color="$BLACK2"; shift; text="$1"; ;;
        --black)        color="$BLACK"; shift; text="$1"; ;;
        --blink)        color="$BLINK"; shift; text="$1"; ;;
        --blue2)        color="$BLUE2"; shift; text="$1"; ;;
        --blue)         color="$BLUE"; shift; text="$1"; ;;
        --bold)         color="$BOLD"; shift; text="$1"; ;;
        --color)        color="$COLOR"; shift; text="$1"; ;;
        --cyan2)        color="$CYAN2"; shift; text="$1"; ;;
        --cyan)         color="$CYAN"; shift; text="$1"; ;;
        --faint)        color="$FAINT"; shift; text="$1"; ;;
        --fraktur)      color="$FRAKTUR"; shift; text="$1"; ;;
        --frame)        color="$FRAME"; shift; text="$1"; ;;
        --green2)       color="$GREEN2"; shift; text="$1"; ;;
        --green)        color="$GREEN"; shift; text="$1"; ;;
        --magenta2)     color="$MAGENTA2"; shift; text="$1"; ;;
        --magenta)      color="$MAGENTA"; shift; text="$1"; ;;
        --red2)         color="$RED2"; shift; text="$1"; ;;
        --red)          color="$RED"; shift; text="$1"; ;;
        --resetbg)      color="$RESETBG"; shift; text="$1"; ;;
        --resetcolor)   color="$RESETCOLOR"; shift; text="$1"; ;;
        --resetfg)      color="$RESETFG"; shift; text="$1"; ;;
        --rgb)          color="$RGB"; shift; text="$1"; ;;
        --underline)    color="$UNDERLINE"; shift; text="$1"; ;;
        --white2)       color="$WHITE2"; shift; text="$1"; ;;
        --white)        color="$WHITE"; shift; text="$1"; ;;
        --yellow2)      color="$YELLOW2"; shift; text="$1"; ;;
        --yellow)       color="$YELLOW"; shift; text="$1"; ;;
            *)
                shift
                ;;
        esac

        if [ -n "$color" ]; then
            # result+="$(echo -e "${color}${text}\033[0m")\n"
            result+="$(echo -e "${color}${text}\033[0m")"
        fi
        color=""
        shift
    done

    echo -e "$result"
}

# Example usage
clr --black 'this white text' --green 'my text is green' --bold 'Im the bold'
clr --black2 'this white text' --yellow2 'my text is green' --red2 'Im the bold'
clr --faint 'this faint' --bgwhite 'frame text' --fraktur 'Im the bold'
clr --red 'this faint' --bgwhite 'frame text' --fraktur 'Im the bold'

