#!/bin/sh


_cleanup(){

	_trim_duplicate_lines "$TT_VAR/sub_recent_files.ttvar"
	_trim_head "$TT_VAR/LastPWD.ttvar"
	
	> "$TT_TEMP"
	_last_run
}

_trim_duplicate_lines(){
	cat "$1" | liner uniq > "$TT_TEMP"
	cat "$TT_TEMP" > "$1"
}

_trim_head(){
	head -n 7 "$1" | liner exist > "$TT_TEMP"
	cat "$TT_TEMP" > "$1"
}

_last_run(){
	time=$(date)
	item="# Last run at: $time"
	# sed -i '3c'"$item" "${0}"
	term=$(tty)
	echo "sublime on_exit: last exiter run at: $time" > $term
	echo "sublime on_exit: last exiter run at: $time" >> ~/terabo
}

_cleanup
