#!/bin/sh


fn_one(){	# Select one from PIPE input
	shift
	data="$@"
	item=`cat | fzy -e "$data"`

	count=`echo "$item" | tr ' ' '\n' | wc -l`

	if [ "$count" -lt 3 ]; then

		item=`echo "$item" | fzy -e "$data" | tail -n 1`
	else
		item=`echo "$item" | fzy -q "$data"`
	fi

	echo "$item"

}

fn_onef(){	# Select one from PIPE input
	shift
	data="$@"
	# --tiebreak= length|chunk|begin|end|index
	item=$(cat | fzf --no-sort -1 -f "$data" -q "$data" )

	count=$(echo "$item" | tr ' ' '\n' | wc -l)

	if [ "$count" -eq 1 ]; then
		echo "$item"
	elif [ "$count" -eq 0 ]; then
			echo 0
	elif [ "$count" -eq 2 ]; then
		echo "$item" | head -n 1
	else
		echo "$item" | fzy -q "$data"

	fi
}

fn_two(){
	shift
	q="$@"
	fzf -1 --height=40% --layout=reverse -q "${q}" \
	-d '/' --with-nth=-2,-1
}

"fn_$1" "$@"