#!/bin/sh
set -e

fn_one(){	# Select one from PIPE input
	shift
	data="$@"
	item=`cat | fzy -e "$data"`

	count=`echo "$item" | tr ' ' '\n' | wc -l`

	if [ "$count" -lt 3 ]; then

		item=`echo "$item" | fzy -e "$data" | tail -n 1`
	else
		item=`echo "$item" | fzy -q "$data"`
	fi

	echo "$item"

}

fn_one2(){	# Select one from PIPE input

	data="$@"
	item=$(cat | fzy -e "$data")

	count=$(echo "$item" | tr ' ' '\n' | wc -l)

	if [ "$count" -ne 0 ]; then
		item="$(echo "$item" | fzy -q "$data")"
	fi

	echo "$item"

}

"fn_$1" "$@"