#!/bin/bash

fn_add(){	# Add multiple files and commit msg

	item=$(_first_uncommit_file)
	desc=$(_read-desc)
	shift
	git add "$@"
	git commit -m "$item - $desc"

}

fn_all(){	# Auto Add files and commit msg

	item=$(_first_uncommit_file)
	fn_ls
	
	desc=$(_read-desc)
	git commit -a -m "$item - $desc"

}

fn_single(){	# Add single file and commit
	local thefile="$2"

	item=$(_first_uncommit_file)
	[ -z "$item" ] && echo 'no uncommit file..' && exit 7
	[ ! -f "$thefile" ] && echo 'no file arg..' && exit 7

	desc=$(_read-desc)
	git add "$thefile"
	git commit -m "$item - $desc"
}

fn_commit(){	# Add  commit msg only
	item=$(_first_uncommit_file)
	desc=$(_read-desc)
	git commit -m "$item - $desc"
}


fn_ls(){	# list uncommit files
	git diff --name-only
}

fn_branch(){	# get current branch
	git branch
	git branch --show-current
}

_first_uncommit_file(){
	git diff --name-only | sed -n '1p'
}

_read-desc(){
	read -rp "Descriptions $ARROW " _desc
	[ -z "$_desc" ] && echo 'empty description..' && exit 7
	echo "$_desc"
}

"fn_$1" "$@"