#!/bin/bash
set -e

fn_untar(){   # Untar the tar files
    item=`fd '.*tar.*?' -t f -d 2 | fzy`

    [ $? -ne 0 ] && show_msg2 "CANCEL" "Operation..." && exit 7
    [ -z "$item" ] && show_msg2 "ERROR" "Empty" && exit 7

    case "$item" in

        *.tar) tar -xvf "$item" ;;
        *.tar.gz) tar -xzf "$item" ;;
        *.tar.bz2) tar -xjf "$item" ;;
        *.tar.xz) tar -xJf "$item" ;;
        *.tar.lz) tar --lzip -xf "$item" ;;
        *.tar.zst) tar --zstd -xf "$item" ;;
        *.tar.lz4) tar --lz4 -xf "$item" ;;
        *) echo "Unsupported file extension: $item" ;;

    esac

}


fn_move(){    # move the Latest files to HOME directories

    cd "$MYFILES"

    item=$(ls -ltu $(fd -H -I -t f -d 1 . $MYFILES) |
     head -n 1| awk '{print $NF}')

    echo "$item"

    show_confirm

    [ $? -ne 0 ] && exit 7

    mv "$item" ~

}


fn_unzip(){
    unzip "$2"
}


"fn_$1" "$@"
