#!/bin/bash

itemvar=prompt
not_end=true


edit(){
	while $not_end; do
		reader
	done
}


_confirm(){
	echo "$itemvar"
	not_end=false
	exit 0
}


_update(){
	itemvar+="$1"
	tput el
	echo -n "$1"
	# tput cuu1
}


read_key(){

	IFS=''
	read -rsn1 mode

	if [ "$mode" = $'\x1b' ]; then
		read -rsn2 -t 0.01 mode
		[ "$mode" = '' ] && echo "esc" && return
	fi

	echo "${mode}"
}

reader(){

	local mode
	mode=$(read_key)

	case "$mode" in
		[0-9]) echo "$mode" ;;
		'[A') echo UP ;;
		'[B') echo DN ;;
		'[D') echo LEFT ;;
		'[C') echo RIGHT ;;
		$'\t') echo TAB ;;
		'esc') echo ESCAPE ;;
		$' ') _update ' ' ;;
		$'') _confirm 	;;
		*) _update $mode ;;
	esac

}

# read_key