#!/bin/bash
# Jump with toogle behaviour

_jumpfile="${TT_VAR}/jump_files.ttpath"
_jumpdir="${TT_VAR}/jump_folders.ttpath"

fn_db(){	# open jump [file | folder] in editor

	item=$( { echo '$TT_VAR/jump_files.ttpath'; echo '$TT_VAR/jump_folders.ttpath'; } | fzy )
	item=$(eval "echo \"${item}\"")
	st open "$item"

}


fn_rmd(){	# Delete Line from choosen [Jump Directory]
	eline d "$_jumpdir"
}

fn_rmf(){	# Delete Line from choosen [Jump file]
	eline d "$_jumpfile"
}

fn_lsf(){	# Cat ls [Jump file]
	cat "${_jumpfile}"
}


fn_lsd(){	# Cat ls [Jump Directory]
	cat "${_jumpdir}"
}


fn_open(){	# open jump [file | folder]
	set -e
	shift
	arg="$@"

	item=`fn_lsf | awk -F'/' '{print $(NF)}' | fuzzy one "$arg"`

	item=`rg "$item" -F "$_jumpfile" | fzy -e "$item"`

	item=`eval echo "${item}"`
	
	st open "${item}"

}

fn_openat(){	# open file at choosen folder

	shift
	argd="$1"
	argf="$2"

	item=`fn_lsd  | fuzzy onef "$argd"`
	todir=`eval echo "$item"`

	(
		cd "$todir"
		[ -z "$argf" ] && argf2='.' || argf2="${argf}*"
		thefile=`fd "$argf2" -t f -d 2 | fuzzy onef "$argf"`

		item="$todir/${thefile}"
		st open "$item"
		varm append_recents "$item" 'sub_recent_files'
	)

}

fn_openr() {	# open from recents list
	recents="$TT_VAR/sub_recent_files.ttvar"
	item=`_fzfone "$2" < "$recents" `
	item=$(eval "echo \"$item\"")

	st open "$item"
	varm append_recents "$item" 'sub_recent_files'
}

_fzfone(){
	fzf -1 --height=40% --layout=reverse -q "${1}" \
	-d '/' --with-nth=-2,-1
}

fn_file() {	# add to jump files

	item=$(fd . -H -t f -d 2 | fuzzy one "${2}")

	[ ! "${item}" ] && message "CANCEL" "Operation..." && exit 7

	filepath=$(varm relative "$item")

	_append_uniq "${filepath}" "$_jumpfile"
	message "DONE add : " "$filepath"

}

fn_dir() {	# add folder to jump list

	filepath=$(varm relative ".")
	_append_uniq "${filepath}" "$_jumpdir"
	echo $?
	message "DONE add : " "$filepath"

}

_append_uniq(){	# append at top of file and uniq then remove empty line
	{
		cat "${2}"
		echo "$1"
	} > "${TT_TEMP}"

	awk '!seen[$0]++ && NF' < "${TT_TEMP}" > "${2}"

}

fn_make(){	# reconstruct all jump lists

	rargs varm relative {} < "$_jumpfile" > "$TT_TEMP"
	mv "$TT_TEMP" "$_jumpfile"

	rargs varm relative {} < "$_jumpdir" > "$TT_TEMP"
	mv "$TT_TEMP" "$_jumpdir"
	
}

"fn_$1" "$@"
