#!/bin/bash
#FILE! line editing tools


fn_append(){
	sed -i "${index}a\\${new}" "${filepath}"
}

fn_change(){
	sed -i "${index}c\\${new}" "${filepath}"
}

fn_delete(){
	sed -i "${index}d" "${filepath}"
}

fn_from(){	# Convert delimiter into Lines
	tr "$2" '\n'
}

fn_space(){	# Convert Spaces to Lines
	tr ' ' '\n'
}

fn_join(){	# join Lines to delimiter
	sd '\n$' '' | sd '\n' "$2"
}

fn_trim(){	# trim any empty line
	awk 'NF'
}

fn_concat(){	# join multiple Lines by % into single line
	awk -v idx="$2" '{ORS = (NR % idx ? " " : RS)} 1'
}

#get line area --------------------------------------

fn_getat(){	# awk get line at index
	awk "NR==$2 {print; exit}" "$3"
}

fn_uniq(){	# awk get uniq line no duplicate
	awk '!seen[$0]++' "$3"
}

fn_count(){	# awk get line at index
	echo "$2" | wc -l
}



"fn_$1" "$@"
