#!/bin/bash
#FILE! line editing tools

fn_seq(){	# generate seq empty lines
	awk -v count=$2 'BEGIN { for (i = 1; i <= count; i++) {print "" } }'
}

fn_append(){
	sed -i "${2}a\\${3}" "${4}"
}

fn_change(){
	sed -i "${2}c\\${3}" "${4}"
}

fn_delete(){
	sed -i "${2}d" "${3}"
}

fn_from(){	# Convert delimiter into Lines
	tr "$2" '\n'
}

fn_space(){	# Convert Spaces to Lines
	tr ' ' '\n'
}

fn_join(){	# join Lines to delimiter 
	item="${2:- }"
	item=$(tr '\n' "$item")
	echo "${item%?}" # remove last char
}

fn_trim(){	# trim any empty line
	awk 'NF'
}

fn_concat(){	# join multiple Lines by % into single line
	awk -v idx="$2" '{ORS = (NR % idx ? " " : RS)} 1'
}

#get line area --------------------------------------

fn_getat(){	# awk get line at index
	awk "NR==$2 {print; exit}" "$3"
}

fn_uniq(){	# awk get uniq line no duplicate
	awk '!seen[$0]++' "$3"
}

fn_count(){	# awk get line at index
	echo "$2" | wc -l
}



"fn_$1" "$@"
