#!/bin/sh

fn_new(){

	item="$2"
	[ -z "$item" ] && color 'Missing: Argument: name?' && exit 7
	
	cp "$TT_VAR/template.sh" "$item"
	chmod 700 "$item"
	ls

}


fn_ls(){
	ls "$TT_BASH/micro"
}



"fn_$1" "$@"