#!/bin/sh


fn_new(){
	
	cd "$TT_BASH/micro"
	alif="$2"
	newsh "$alif"

	wait
	if [ -e "$alif" ]; then
		color "Add: file $alif : to git"
		gitt add "$alif"
		st open "$alif"
	fi

}


fn_ls(){
	ls "$TT_BASH/micro"
}



"fn_$1" "$@"