#!/bin/bash
#FILE! Player for testing scripts

# save into scripts db
dbfile="$TT_VAR/bash_script_play.ttdb"
play_file="$TT_BASH/scripts/_play_runner"
SAPERATOR="#::=>PLAY!"
PLAY_TITLE="#TITLE!"


fn_new() {	# create new PLAY item [-s] for save

	if [ ${!#} == '-s' ]; then
		fn_save
	fi

	{
		echo "#!/bin/bash"
		echo "${PLAY_TITLE} "
		echo ""
		echo "echo hello TERABO"
	} > "$play_file"

	st reload "$play_file"

}


fn_save() {	# save PLAY item into db with title

	local title

	_title=$(tool line 2 "$play_file")
	if [[ $_title == "$PLAY_TITLE"* ]]; then

		_title=`echo $_title | tool cutd '!' 2- |  tool trim`
		if [ -z "$_title" ]; then

			if ! title=$(show input 'Save it?'); then
				color "Empty!: Cancel: Operations."
				exit 7
			fi

		else
			title="$_title"
		fi

	fi

	newdate=$(date +%Y-%m-%d)
	{
		echo "${SAPERATOR}$title:$newdate"
		awk 'NR>1 {print}' "$play_file"
	} >> "$dbfile"

}


fn_select() {	# search & select Play item
	set -e
	item=$(_search)
	[ -z "$item" ] && color 'User: Canceling...' && exit 7

	{
		echo "#!/bin/bash"
		echo "$item" 
	} > "$play_file"
	st reload "$play_file"
}


fn_last() {	# search & view LAST Play item

	item=$(rg "^${SAPERATOR}" -n  "$dbfile"| sd "${SAPERATOR}" "" \
	| cut -d: -f 1,2| tail -n 1)
	{
		echo "#!/bin/bash"
		_get_code "$item"
	} > "$play_file"

	st reload "$play_file"

}

fn_update() {	# Update Last Play item

	index=$(rg "^${SAPERATOR}" -n  "$dbfile" | 
		sd "${SAPERATOR}" ""|tail -n 1| cut -d: -f1)

	range delete_tail $index "$dbfile"
	fn_save

}

fn_cat() {	# search & view Play item at terminal
	_search
}

fn_ls() {	# list all Play items
	rg "^${SAPERATOR}" "$dbfile"| sd ".*${SAPERATOR}" "" |
	awk -F ':' '{ printf "- %s:\t%s\n", $1, $2 }' |
	column -t -s $'\t' | color
}


fn_db() {	# Open Play Database file
	st open "$dbfile"
}


fn_sub() {	# Open Play file
	st open "$play_file"
}


# ================================================= Private functions


_run() {
	shift
	_play_runner "$@"
}


_search() {

	item=$(rg "^${SAPERATOR}" -n  "$dbfile"| sd "${SAPERATOR}" "" \
	| cut -d: -f 1,2| fzy)
	_get_code "$item"
}


_get_code() {

	item="$1"
	[ -z "$item" ] && echo "Canceling..." && exit 7
	
	line=$(echo "$item" | cut -d: -f1)
	line=$((line+1))

	range until $line "^$SAPERATOR" "$dbfile"
}


if [ "$#" -gt 0 ]; then
	cmd="$1"

	if rg -q "^fn_$cmd" "$0"; then
		"fn_$1" "$@" 
	else
 		_play_runner "$@"
 	fi
else
	_play_runner "$@"
fi
