#!/bin/sh



fn_until(){

	line=$(($2 + 1))
	pattern="$3"
	thefile="$4"

	sed -n "${line},/$3/ {/${3}/d; p;}" "$4"

}

fn_print(){	# print given range 1,2 file
	sed -n "${2},${3}p" "$4"
}

fn_delete_tail(){
	sed -i "$2,\$d" "$3"
}

fn_swap(){	# swap by 2 given rangle

	shift

	one1=$1
	one2=$2
	two1=$3
	two2=$4
	item="$5"

	[ "$#" -ne 5 ] && echo "need 4 args" && exit 7
	[ ! -f "$item" ] && echo "no such file" && exit 8

	first=$((two1-1))
	secd=$((one1-1))

	ex -s \
	-c "${one1},${one2}m${first}" \
	-c "$two1,${two2}m${secd}" -c x "${item}"

}


fn_swap_single(){	# swap by 2 given index
	shift

	one1=$1
	two1=$2

	first=$((two1-1))
	secd=$((one1-1))

	ex -s \
	-c "${one1}m${first}" \
	-c "${two1}m${secd}" -c x "${3}"

}


fn_ls_bash(){	# Get all file with shebang

	rg '#!/bin/(bash|sh)' --fixed-strings --files-with-matches
	awk '/^/w+/,/^}/' "$1"

}


"fn_$1" "$@"
