#!/usr/bin/env python3
import tkinter as tk
import sys

def remove_word_backward(event):
	curr = textbox.index(tk.INSERT)  # Get current cursor position
	line, column = map(int, curr.split('.'))
	
	# Go back one character to check if it's a space
	if column > 1:
		prev_char = textbox.get(f"{line}.{column - 1}")
		if prev_char.isspace():
			# Remove the word
			textbox.delete(f"{line}.{column - 2}", curr)
			return
	
	# If the character is not a space, delete until a space is found
	while column > 1:
		prev_char = textbox.get(f"{line}.{column - 1}")
		if prev_char.isspace():
			break
		textbox.delete(f"{line}.{column - 1}")
		column -= 1
		
def close_window(event=None):
	window.destroy()

def on_enter_pressed(event):

	text = textbox.get("1.0", "end-1c")
	print(text)
	window.destroy()

def create_window():
	window = tk.Tk()
	
	# window.overrideredirect(1)  # headless window
	window.wm_attributes('-type', 'splash')
	screen_width = window.winfo_screenwidth()
	screen_height = window.winfo_screenheight()
	half_screen_width = 600
	x = y = 0
	window.geometry(f"{half_screen_width}x{150}+{x}+{y}")
	window.configure(background=bg_color)
	return window

def create_frame(window):
	frame = tk.Frame(window, bg=bg_color)
	frame.pack(fill=tk.BOTH, expand=True)
	return frame

def create_textbox(frame):
	textbox = tk.Text(frame)
	textbox.pack(fill=tk.BOTH, expand=True, padx=7, pady=10)
	textbox.bind('<Shift-Return>', on_enter_pressed)
	textbox.bind("<Control-BackSpace>", remove_word_backward)

	textbox.configure(bg=inputbg, fg="white", bd=0, font=("Fira Code", fontsize + 1))
	textbox.focus_set()
	return textbox

if __name__ == "__main__":
	
	bg_color = '#2E3440'
	inputbg = "#2E3441"
	fontsize = 14

	window = create_window()
	frame = create_frame(window)
	textbox = create_textbox(frame)

	line = sys.stdin.readline().strip()

	argument = sys.argv[1] if len(sys.argv) > 1 else ""
	textbox.insert(tk.END, line)

	window.mainloop()
