#!/bin/bash
#FILE! ripgrep commands


. $TT_BASH/alias_cmd


fn_ls(){

	item="$(list_var 'RG_Regexs' | fzy)"
	echo ${item} | awk -F':=>' '{print $2}'

}


fn_open(){

	item="$(get_var_file 'RG_list')"
	st open "$item"

}


fn_regex(){

	item="$(get_var_file 'RG_Regexs')"
	st open "$item"

}


fn_option(){
	item="$2"
	full='[-]\w,\s(--)\w+'
	simple='^\s*[-]+\w*'

	# check if $1 is -s, cmd =simple else full
	[[ $1 == "-s" ]] && regex="$simple" || regex="$full"

    data=$("${@: -1}" --help)

    echo "$data"  | rg --trim "$regex" --color=never |
    sd -F '.' ''

}



"fn_$1" "$@"