#!/bin/bash
#TITLE! find multiple pattern using rg ripgrep

# max count 1 all but not 1st
do_match(){

	run1(){
		rg "$1" -n --color=always --colors match:fg:green
	}
	run2(){
		run1 "$1" | 
		rg "$2" --color=always --colors match:fg:cyan
	}
	run3(){
		run2 "$1" "$2" | 
		rg "$3" --color=always --colors match:fg:red
	}
	run4(){
		run3  "$1" "$2" "$3" | 
		rg "$4" --color=always --colors match:fg:green
	}
	run5(){
		run3  "$1" "$2" "$3" "$4" | 
		rg "$5" --color=always --colors match:fg:white
	}

	"run$len" "$@"

}

do_match2() {
    local colors=("green" "cyan" "red" "green" "white")
    local command="rg \"$1\" -n --color=always --colors match:fg:${colors[0]}"

    for ((i = 1; i < $#; i++)); do
        command+=" | rg \"\$$((i+1))\" --color=always --colors match:fg:${colors[$i]}"
    done

    eval "$command"
}

do_nocolor(){

	run1(){
		rg "$1" -n --color=never
	}
	run2(){
		run1 "$1" | rg "$2" --color=never
	}
	run3(){
		run2 "$1" "$2" | rg "$3" --color=never
	}
	run4(){
		run3  "$1" "$2" "$3" | rg "$4" --color=never
	}
	run5(){
		run3  "$1" "$2" "$3" "$4" | rg "$5" --color=never
	}

	"run$len" "$@"
}

do_replace(){
	local allfile

	while read -r line; do
		item="$line"
		thefile=$(echo "$item" | tool cut 1)
		index=$(echo "$item" | tool cut 2)
		value=$(echo "$item" | tool cut 3)

		echo "$value : at $index"
		allfile+="$thefile "

	done
	echo "$allfile"
	# show confirm 'Confirm: to: Proceed'

}

do_restore(){
	echo
	# git restore here
}

#TODO! create cmd for replacement
#TODO! replacement cant be colors


len="$#"
[ $len -eq 0 ]&& exit 7

if [ "$1" = '-n' ]; then
	shift
	len=$((len-1))

	do_nocolor "$@"
elif [ "$1" = '--run' ]; then
	do_replace
else
	do_match2 "$@"
fi
