#!/bin/bash


fn_success(){
  if [ $? -eq 0 ]; then
      return 0
  else
      return 7
  fi

}

fn_failed(){
  if [ $? -ne 0 ]; then
      exit 7
  else
      exit 0
  fi
}

fn_input(){

  promp=`color -i 2 "${2}: ❯ "`

  read  -rp "$promp" inputs

  if [ -z "$inputs" ]; then
    exit 7
  else
    echo "$inputs"
  fi

}


fn_message(){
  color "$@"
}

"fn_$1" "$@"
