#!/bin/sh

db_file="$BARTIB_FILE"

_on(){	# starts a new activity
	bartib start -d "$2" -p "$3"
}

_off(){	# stops all currently running activities
	bartib stop
}

_cancel(){	# cancels all currently running activities
	bartib cancel

}

_edit(){	# opens the activity log in an editor
	st open "$BARTIB_FILE"

}
_check(){	# checks file and reports parsing errors
	bartib check
}

_continue(){	# continues a previous activity
	bartib continue
}

_lsc(){	# lists all currently running activities
	bartib current
}

_lsp(){	# list all projects
	bartib project
}

_report(){	# reports duration of tracked activities
	bartib report
}

"_$1" "$@" 