#!/bin/sh

db_file="$BARTIB_FILE"

fn_new(){	# starts a new activity

	[ -z "$2" ] && echo "On must defind Description" && exit 7
	[ -z "$3" ] && echo "On must defind project Name" && exit 7

	bartib start -d "$2" -p "$3"
}

fn_on(){	# starts a new activity
	[ -z "$2" ] && echo "Remember to use Number to On activity"
	bartib continue "${2:-0}"
}

fn_off(){	# stops all currently running activities
	bartib stop
}

fn_cancel(){	# cancels all currently running activities
	bartib cancel

}

fn_edit(){	# opens the activity log in an editor
	st open "$BARTIB_FILE"
}

fn_check(){	# checks file and reports parsing errors
	bartib check
}

fn_resume(){	# continues a previous activity
	bartib continue "${2:-0}"
}

fn_last(){	# displays the descriptions and projects of recent activities
	bartib last
}

fn_ls(){	# list recent activities by Date | Name Date
	bartib list --today
}

fn_yesterday(){	# list recent activities by yesterday
	bartib list --yesterday
}

fn_week(){	# list recent activities by week
	bartib list --current_week
}

fn_lsc(){	# lists all currently running activities
	bartib current
}

fn_lsp(){	# list all projects
	bartib projects
}

fn_report(){	# reports duration of tracked activities
	bartib report
}

"fn_$1" "$@" 