#!/bin/bash


__dynamic_alias(){

	alias_file="$TT_BASH/dynamic_aliases"

	if [ -f '.ttrc' ]; then
		{
			echo "# $PWD"
			cat '.ttrc' 
		} > "$alias_file"
		. "$alias_file"

	else
		#CODE! remove all alias
		.clear "$alias_file"
	fi


}


fn_new(){	# create .ttrc file

	message "Creating: .ttrc file"
	if [ ! -f '.ttrc' ]; then
		echo '#!/bin/sh' > '.ttrc'
	fi
	st open '.ttrc'

}


fn_open(){	# open .ttrc file if aviable

	if [ -f '.ttrc' ]; then
		st open '.ttrc'
	else
		message "ERROR: .ttrc file not aviable!"
	fi

}


fn_clear(){	# remove all ttrc definitions

	alias_file="$TT_BASH/dynamic_aliases"

	if [ -s "$alias_file" ]; then

		while read -r item; do
		    unset "$item"
		done < <(rg -o '^export \w+|^function \w+' "$alias_file" | cut -d ' ' -f2)

		while read -r item; do
			unalias "$item"; 
		done < <(rg '^alias \w+' -o "$alias_file"| cut -d ' ' -f2)

		> "$alias_file"
		# . "$alias_file"
	fi

}



if [ -n "$1" ]; then
	"fn_$1" "$@"
	exit 0
fi


__dynamic_alias