#!/bin/sh

fn_cut(){

	cut -d: -f "$2"
}

fn_triml(){
	awk 'NF'
}


fn_trim(){
	awk '{$1=$1};1'
}

fn_lastf(){
	awk -F "$2" '{print $(NF-1)}'
}

fn_line(){
	awk "NR==$2 {print; exit}" "$3"
}



#CODE! pipe is coming bro..
if [ ! -t 0 ]; then
	"fn_$1" "$@"
	exit
fi

"fn_$1" "$@"
