#!/bin/sh

fn_cut(){	# cut with ':' delimiter

	cut -d: -f "$2"
}

fn_cutd(){	# cut with delimiter. given field position
	del=${2:-:}
	cut -d"$del" -f "$3"
}


fn_trim(){	# trim any extra spaces
	awk '{$1=$1};1'
}

fn_last2f(){	# awk print 2nd last field with delimiter '/' arg
	awk -F "$2" '{print $(NF-1)}'
}

fn_lastf(){	# awk print last field with delimiter '/' arg
	awk -F "$2" '{print $(NF)}'
}

fn_seenspace(){	# awk get line at index
	awk 'BEGIN {RS=" ";} !seen[$0]++ {printf("%s ", $0)}'
}


#CODE! pipe is coming bro..
# if [ ! -t 0 ]; then
# 	"fn_$1" "$@"
# 	exit
# fi

"fn_$1" "$@"
