#!/bin/bash
#TITLE! read tab as tree for editing

thefile="$TT_VAR/tree_structure.ttdb"
topindex=$(rg -n "^#\s\w+" "$thefile" | cut -d: -f1| tr '\n' ' '| warp trim)

tabcount=0
tabchar=


inctab(){
	tabcount=$((tabcount+1))
}

reset_tab(){
	tabcount=0
}

gettab(){

	[ $tabcount -eq 0 ] && printf '' && return
	printf '\t%.0s' $(seq 1 $tabcount)

}

start(){
	rg -N --color=never "^#\s\w+.*" "$thefile" |
	sd '(#)' "$(color --red '$1')" |
	sd '(Task|Wish|Done|Cancel)' "$(color --faint '$1')"
}


goin_all(){
	range print "$1" '$' "$thefile" | 
	awk -v count=$tabcount -F'\t' '{if(NF<count+1) exit; print $0}'
}


showchild(){
	range print "$1" '$' "$thefile" | 
	awk -v count=$tabcount -F'\t' '{if(NF!=count+1) exit; print $0}'
}

show(){
	last=${!#}
	[[ ! $last =~ ^[0-9]+$ ]] && last=1

	index=$(echo "$topindex" | cut -d ' ' -f"$last")

	item=$(sed -n "${index}p" "$thefile")

	color --faint "$item"
	index=$(rg -n "^$item" "$thefile" | cut -d: -f1)

	index=$((index+1))
	tabcount=$((tabcount+1))

	# goin_all $index
	showchild $index
}

view(){
	cat "$thefile"
}

db(){

	st open "$thefile"
}



app(){

	start

	read -erp 'choose item ❯ ' digit
	show "$digit"

}

"$1" "$@"