#!/bin/sh

mem_file='/dev/shm/TtMemory'

fn_init(){
	[ ! -d "$mem_file" ] && mkdir "$mem_file"
	[ ! -p "$TT_IPC" ] && mkfifo "$TT_IPC"
}

fn_setenv(){

	key="$2"
	val="$3"
	echo "$key='$val'"  > "$TT_IPC" &

	# pid=$(ps | rg '^[0-9]+' -o | head -n 1)
	bash -c "kill -s SIGRTMIN $BASHPID"

}

fn_set(){
	printf "$3" > "$mem_file/${2}.ttvar"
}

fn_get(){
	item="$mem_file/${2}.ttvar"
	[ -f "$item" ] && awk 'NR==1 {print}' "$item"
}

fn_get_file(){
	echo "$mem_file/${2}.ttvar"
}

fn_ls(){
	fd . -t f -d 2 --base-directory "$mem_file"
}


"fn_$1" "$@"
