#!/bin/sh

MEM_DIR='/dev/shm/TtMemory'

fn_init(){
	[ ! -d "$MEM_DIR" ] && mkdir "$MEM_DIR"
	[ ! -p "$TT_IPC" ] && mkfifo "$TT_IPC"
}

fn_setenv(){

	key="$2"
	val="$3"
	echo "$key='$val'"  > "$TT_IPC" &
	
	#TODO: fixed kill signal
	pid=$( ps|rg '[0-9]+' -om 1  | sed -n 1p)
	if bash -c "kill -s SIGRTMIN $pid" ;then
		exit 0
	else
		(cat "$TT_IPC")
		exit 7
	fi

}

fn_set(){
	printf "$3" > "$MEM_DIR/${2}.ttvar"
}

fn_get(){
	item="$MEM_DIR/${2}.ttvar"
	[ -f "$item" ] && awk 'NR==1 {print; exit}' "$item"
}

fn_file(){
	echo "$MEM_DIR/${2}.ttvar"
}

fn_ls(){
	cd "$MEM_DIR"; fd . -tf -d 2
}


"fn_$1" "$@"
