#!/bin/bash
#FILE! Bash Templates 

tempf="/dev/shm/tttempfiles"


fn_lower(){	# Convert stdin to lowercase

    tr '[:upper:]' '[:lower:]'
}

fn_upper(){	# Convert stdin to uppercase.

    tr '[:lower:]' '[:upper:]'
}

fn_title(){	# Convert stdin to titlecase.

    fn_lower | sed 's/\<./\u&/g' | sed "s/'[[:upper:]]/\L&\l/g"
}

fn_detox(){	# Make text from stdin slightly less insane

    sed 's/[^A-Za-z0-9 ]/ /g' | squeeze | sed 's/ /_/g' | fn_lower
}

fn_camel(){	# Make text from stdin camel case.

    sed 's/_/ /g' | sed 's/\<\(.\)/\U\1/g' | sed 's/ //g'
}

fn_snake(){	# Make text from stdin snake case

    sed 's/\([[:upper:]]\)/ \1/g' | fn_detox
}

fn_squeeze(){	# Removes leading/trailing whitespace and condenses

    local char=${1:-[[:space:]]}
    sed "s%\(${char//%/\\%}\)\+%\1%g" | fn_trim "$char"
}

# ==================================== TERABOTERABA


fn_pair(){	# surround 2 Pair from lines
	awk -v one="$2" -v two="$3" '{ print one $0 two}'
}

fn_single(){	# surround stdin by Single quote
	awk '{ print "\x27" $0 "\x27" }'
}


fn_double(){	# surround stdin by Double quote
	awk '{ print "\"" $0 "\"" }'
}


fn_head(){	# Append stdin at Head
	awk -v item="$2" '{ print item $0 }'
}


fn_tail(){	# Append stdin at Tail
	awk -v item="$2" '{ print $0 item }'
}

fn_each(){	# generate all args combine with [-] as stdin.
	shift
	while read -r line; do
		echo "${@/-*/$line}"
	done
}


fn_com(){	# Merge from [stdin & args] by a delimiter

	paste -d "$2" - "${tempf}"
}


fn_merge(){	# Merge from [stdin & args] by a delimiter

	sep="$2"
	shift 2
	paste -d "$sep" <(printf "%s\n" "${@}") -

}


fn_mergeawk(){	# Merge awk from [stdin & args] by a delimiter

	sep="$2"
	args=("${@:3}")

	awk -v args="${args[*]}" -v sep="$sep" 'BEGIN {
	    split(args, item);
	    ln = 1;
	}
	{
	    printf("%s%s%s\n", item[ln], sep , $0);
	    ln = (ln % length(item)) + 1;
	}'
}

fn_str(){	# get substring from stdin by delimiter

	while read -r line; do
		ops="$2"
		echo "${line%$ops*}"
	done

}


fn_store(){	# Store to temp then print result
	tee - "$tempf"
}


fn_eval(){	# Take args as command and Eval all Lines
	
	while read -r line; do
		eval "$line"
	done
}


#CODE! pipe is coming bro..
if [ ! -t 0 ]; then
	"fn_$1" "$@"
	exit
fi

"fn_$1" "$@"
